<?php

namespace App\Http\Controllers;

use Illuminate\View\View;

class MobileApiDocsController extends Controller
{
    /**
     * Admin-only mobile API documentation page.
     */
    public function index(): View
    {
        $baseUrl = rtrim(url('/api/v1'), '/');

        $endpoints = [
            [
                'group' => 'Public',
                'method' => 'GET',
                'path' => '/health',
                'auth' => false,
                'summary' => 'API health check',
                'params' => [],
                'body' => null,
                'notes' => 'No auth required.',
            ],
            [
                'group' => 'Public',
                'method' => 'GET',
                'path' => '/app-info',
                'auth' => false,
                'summary' => 'Mobile app feature flags / support info',
                'params' => [],
                'body' => null,
                'notes' => 'No auth required.',
            ],
            [
                'group' => 'Authentication',
                'method' => 'POST',
                'path' => '/login',
                'auth' => false,
                'summary' => 'Meter reader / admin login — returns Sanctum token',
                'params' => [],
                'body' => [
                    'email' => 'required|email',
                    'password' => 'required|string|min:6',
                    'device_name' => 'required|string',
                    'device_info' => 'nullable|array',
                ],
                'notes' => 'Allowed roles: admin, meter_reader, supervisor. Token scopes: meter-reading.',
            ],
            [
                'group' => 'Authentication',
                'method' => 'POST',
                'path' => '/logout',
                'auth' => true,
                'summary' => 'Revoke current access token',
                'params' => [],
                'body' => null,
                'notes' => null,
            ],
            [
                'group' => 'Authentication',
                'method' => 'POST',
                'path' => '/refresh',
                'auth' => true,
                'summary' => 'Refresh / rotate token',
                'params' => [],
                'body' => null,
                'notes' => null,
            ],
            [
                'group' => 'Authentication',
                'method' => 'GET',
                'path' => '/check-token',
                'auth' => true,
                'summary' => 'Validate current token',
                'params' => [],
                'body' => null,
                'notes' => null,
            ],
            [
                'group' => 'Authentication',
                'method' => 'GET',
                'path' => '/profile',
                'auth' => true,
                'summary' => 'Get logged-in user profile',
                'params' => [],
                'body' => null,
                'notes' => null,
            ],
            [
                'group' => 'Authentication',
                'method' => 'PUT',
                'path' => '/profile',
                'auth' => true,
                'summary' => 'Update logged-in user profile',
                'params' => [],
                'body' => [
                    'name' => 'optional',
                    'email' => 'optional',
                    'password' => 'optional',
                ],
                'notes' => 'See AuthApiController for exact validation rules.',
            ],
            [
                'group' => 'Meter Reading',
                'method' => 'GET',
                'path' => '/meter-reading/route/today',
                'auth' => true,
                'summary' => "Today's customer route list for field reader",
                'params' => [],
                'body' => null,
                'notes' => 'Returns active customers with meter + last reading.',
            ],
            [
                'group' => 'Meter Reading',
                'method' => 'GET',
                'path' => '/meter-reading/customers/search',
                'auth' => true,
                'summary' => 'Search customers by name, account, phone, address',
                'params' => [
                    'search|q' => 'required string',
                    'limit' => 'optional, max 50 (default 20)',
                ],
                'body' => null,
                'notes' => 'Active customers only.',
            ],
            [
                'group' => 'Meter Reading',
                'method' => 'GET',
                'path' => '/meter-reading/customers/{customerId}',
                'auth' => true,
                'summary' => 'Customer detail + active meter + recent readings',
                'params' => [
                    'customerId' => 'path — customer id',
                ],
                'body' => null,
                'notes' => null,
            ],
            [
                'group' => 'Meter Reading',
                'method' => 'GET',
                'path' => '/meter-reading/customers/{customerId}/history',
                'auth' => true,
                'summary' => 'Last 12 meter readings for customer meter',
                'params' => [
                    'customerId' => 'path — customer id',
                ],
                'body' => null,
                'notes' => null,
            ],
            [
                'group' => 'Meter Reading',
                'method' => 'POST',
                'path' => '/meter-reading/submit',
                'auth' => true,
                'summary' => 'Submit a new meter reading (online or offline catch-up)',
                'params' => [],
                'body' => [
                    'customer_id' => 'required|exists:customers,id',
                    'meter_id' => 'nullable|exists:water_meters,id',
                    'current_reading' => 'required|numeric|min:0',
                    'reading_date' => 'required|date',
                    'gps_latitude' => 'nullable|numeric',
                    'gps_longitude' => 'nullable|numeric',
                    'meter_photo' => 'nullable|image|max:5120KB',
                    'notes' => 'nullable|string|max:500',
                    'meter_condition' => 'nullable|in:good,damaged,broken,needs_repair',
                    'reading_accuracy' => 'nullable|in:exact,estimated,calculated,actual',
                    'offline_timestamp' => 'nullable|date',
                ],
                'notes' => 'Use multipart/form-data when uploading meter_photo. Current reading must not be less than previous for cumulative meters.',
            ],
            [
                'group' => 'Meter Reading',
                'method' => 'POST',
                'path' => '/meter-reading/bulk-sync',
                'auth' => true,
                'summary' => 'Bulk upload offline readings',
                'params' => [],
                'body' => [
                    'readings' => 'array of reading payloads',
                ],
                'notes' => 'For offline sync queue upload.',
            ],
            [
                'group' => 'Meter Reading',
                'method' => 'GET',
                'path' => '/meter-reading/readings/recent',
                'auth' => true,
                'summary' => "Current reader's last 20 submitted readings",
                'params' => [],
                'body' => null,
                'notes' => null,
            ],
            [
                'group' => 'Meter Reading',
                'method' => 'GET',
                'path' => '/meter-reading/stats',
                'auth' => true,
                'summary' => 'Reader dashboard stats (today / month / performance)',
                'params' => [],
                'body' => null,
                'notes' => null,
            ],
            [
                'group' => 'QR Codes',
                'method' => 'POST',
                'path' => '/meter-reading/qr-code/generate',
                'auth' => true,
                'summary' => 'Generate QR for a meter',
                'params' => [],
                'body' => [
                    'meter_id' => 'required',
                ],
                'notes' => null,
            ],
            [
                'group' => 'QR Codes',
                'method' => 'POST',
                'path' => '/meter-reading/qr-code/scan',
                'auth' => true,
                'summary' => 'Resolve scanned QR payload to meter/customer',
                'params' => [],
                'body' => [
                    'qr_data' => 'required scanned content',
                ],
                'notes' => null,
            ],
            [
                'group' => 'QR Codes',
                'method' => 'GET',
                'path' => '/meter-reading/qr-code/download/{meter_id}',
                'auth' => true,
                'summary' => 'Download meter QR image',
                'params' => [
                    'meter_id' => 'path',
                ],
                'body' => null,
                'notes' => null,
            ],
            [
                'group' => 'QR Codes',
                'method' => 'POST',
                'path' => '/meter-reading/qr-code/batch-generate',
                'auth' => true,
                'summary' => 'Batch generate QR codes',
                'params' => [],
                'body' => [
                    'meter_ids' => 'array',
                ],
                'notes' => null,
            ],
            [
                'group' => 'Payments',
                'method' => 'GET',
                'path' => '/payments/customer/{customer_id}/bills',
                'auth' => true,
                'summary' => 'List bills for payment collection',
                'params' => [
                    'customer_id' => 'path',
                    'status' => 'optional query: generated|sent|overdue|paid',
                ],
                'body' => null,
                'notes' => null,
            ],
            [
                'group' => 'Payments',
                'method' => 'POST',
                'path' => '/payments/record',
                'auth' => true,
                'summary' => 'Record a field payment against a bill',
                'params' => [],
                'body' => [
                    'customer_id' => 'required|exists:customers,id',
                    'bill_id' => 'required|exists:bills,id',
                    'payment_amount' => 'required|numeric|min:0.01',
                    'payment_method' => 'required|in:cash,card,bank_transfer,mobile_payment,cheque',
                    'payment_date' => 'required|date',
                    'transaction_reference' => 'nullable|string',
                    'notes' => 'nullable|string|max:500',
                    'receipt_photo' => 'nullable|image',
                    'gps_latitude' => 'nullable|numeric',
                    'gps_longitude' => 'nullable|numeric',
                ],
                'notes' => null,
            ],
            [
                'group' => 'Payments',
                'method' => 'GET',
                'path' => '/payments/customer/{customer_id}/history',
                'auth' => true,
                'summary' => 'Payment history for a customer',
                'params' => [
                    'customer_id' => 'path',
                    'limit' => 'optional',
                    'from_date' => 'optional date',
                    'to_date' => 'optional date',
                ],
                'body' => null,
                'notes' => null,
            ],
            [
                'group' => 'Payments',
                'method' => 'GET',
                'path' => '/payments/customers/search',
                'auth' => true,
                'summary' => 'Search customers with outstanding balances',
                'params' => [
                    'search' => 'required string',
                    'limit' => 'optional max 50',
                ],
                'body' => null,
                'notes' => null,
            ],
            [
                'group' => 'Sync',
                'method' => 'GET',
                'path' => '/sync/pending',
                'auth' => true,
                'summary' => 'Pending upload count / last sync (stub for offline)',
                'params' => [],
                'body' => null,
                'notes' => 'Currently returns placeholder pending_uploads=0.',
            ],
            [
                'group' => 'Sync',
                'method' => 'POST',
                'path' => '/sync/force',
                'auth' => true,
                'summary' => 'Force sync acknowledgement (stub)',
                'params' => [],
                'body' => null,
                'notes' => null,
            ],
            [
                'group' => 'Utils',
                'method' => 'GET',
                'path' => '/utils/areas',
                'auth' => true,
                'summary' => 'List areas (not implemented yet)',
                'params' => [],
                'body' => null,
                'notes' => 'Returns empty collection + message.',
            ],
            [
                'group' => 'Utils',
                'method' => 'GET',
                'path' => '/utils/routes',
                'auth' => true,
                'summary' => 'List routes (not implemented yet)',
                'params' => [],
                'body' => null,
                'notes' => 'Returns empty collection + message.',
            ],
            [
                'group' => 'Utils',
                'method' => 'GET',
                'path' => '/utils/system-info',
                'auth' => true,
                'summary' => 'Server time, timezone, versions, maintenance flag',
                'params' => [],
                'body' => null,
                'notes' => null,
            ],
        ];

        $grouped = collect($endpoints)->groupBy('group');

        $loginExample = [
            'email' => 'reader1@aquabill.olexto.com',
            'password' => 'password',
            'device_name' => 'android-pixel-1',
            'device_info' => [
                'brand' => 'Google',
                'model' => 'Pixel',
                'os' => 'Android',
            ],
        ];

        $submitExample = [
            'customer_id' => 1,
            'meter_id' => 1,
            'current_reading' => 1250.5,
            'reading_date' => now()->toDateString(),
            'gps_latitude' => 6.9497,
            'gps_longitude' => 80.7891,
            'notes' => 'Clear access',
            'meter_condition' => 'good',
            'reading_accuracy' => 'actual',
        ];

        return view('mobile-api.index', compact(
            'baseUrl',
            'grouped',
            'loginExample',
            'submitExample'
        ));
    }
}
